### ISSUE TITLE
starlink.update.sh is not running

### ISSUE THREAD

**Issue by MyGreenBodhi** [ChuckTSI/BetterThanNothingWebInterface#8]
Hey Chuck, 
I have a FAMP Server on my Freenas Box,..I have it running your package...the page loads (but seems to have fake data) and top says "It seems as though your starlink.update.sh is not running. This message will go away once you fix the issue"

Could you point me in the right direction? Thanks for the awesome tool

**Comment by ChuckTSI** [comment]
If you just want to get it up and running quick, go into the config.inc.php file and look for this:
$_CONFIG["dishy"]['update_method'] = 'CLI';    
Change it to:
$_CONFIG["dishy"]['update_method'] = 'BROWSER';   

If you want your server to constantly collect data without leaving your browser open, leave it to CLI  and you will need to figure out a way to run the scripts/binbash/starlink_update.sh script) in the background. Only need to run it once as it loops until you kill it. 

You may be able to run it as a deamon process     ./starlink_update.sh &

**Comment by MyGreenBodhi** [comment]
Thanks for that... I still have something amiss, I get a UL Unresponsive,
even though I can reach Dishy from my browser directly.  Could it be
GRPCurl is not set up correctly... I will poke around.

Thanks,
Rob

**Comment by woodseowl** [comment]
@MyGreenBodhi Did you get it working? I was having UL Unresponsive when running this under Docker. Not sure if my fixes are applicable, but for Docker:

- When I ran `docker up` rather than `docker up -d` I was able to watch and see that it wasn't finding a script. 
- In `scripts/binbash/starlink.update.sh` I had to switch that to include `btnwi` in the path (`/var/www/html/btnwi/...`). 
- Same path update in a couple places in `config.inc.php`. 
- I think I also had to create and empty data/obstructions_log.csv file. 

Happy to provide a pull request for review @ChuckTSI , if you'd like it.

(I also had a heck of a time debugging a network problem in my local MacOS Docker config, because apparently it had used 192.168.65.0/24 as internal network and that meant getting to 192.168.100.1 just wasn't happening. But that was my problem not this repo. FYI, fix was vi Docker Desktop config of network settings, but that didn't take until I did a full host computer restart.)

**Comment by MyGreenBodhi** [comment]
Yes, I did. I got to spend some time today on it.
Waiting for a speed test to complete, just to make sure that part is
working properly...otherwise it is up and running.

**Comment by ChuckTSI** [comment]
I ran over my dishy cable with a snowblower. So I am out. I can definitely use the help so anything you can throw this way.. or if any of you want to take this version and start up copy. I can take this one down and point it to yours.

**Comment by woodseowl** [comment]
Noooo! Oh that is dreadful. FWIW, I saw someone post that Starlink helped in a situation like that.

I’ll get a PR for the changes I needed to get things working, so that at least can be available to help others. 

I am going a different direction for my own interest: RaspberryPi & hardware for displaying info. It’ll use PHP, so I may have something to contribute down the line.

**Comment by ChuckTSI** [comment]
Very cool. Look forward to seeing it. :)
